### ISSUE TITLE
[Bug Report] <Can't moce mailbox window>

### ISSUE THREAD

**Issue by MerVidiuM** [Kiatra/BlizzMove#102]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

I open my mailbox and try to move the mail window, the mail window goes blank.
This only happens with Elvui enabled.

### Steps to reproduce.

Open mailbox and try to move the window with eldui enabled.

### Expected behavior.

I expected the window to move like before.

### Errors

```lua
BlizzMove: The frame you just moved (MailFrame) is probably in a broken state, possibly because of other addons. Copy the text from this popup window, and report it to the addon author.

Bad anchor connections for "MailFrame":


"OpenMailSenderLabel" is outside anchor family, but referenced by "OpenMailSender" (created in "Interface/FrameXML/MailFrame.xml:962")

"UIParent.24c176a1260" is outside anchor family, but referenced by "MailFrameInset" (created in "Interface/SharedXML/SharedUIPanelTemplates.xml:1112")
```

**Comment by Numynum** [comment]
what blizzmove version are you using? this was fixed a few days ago
