### ISSUE TITLE
[Feature Request] Move collection frame when Soulshape Journal addon is open

### ISSUE THREAD

**Issue by martinboy1974** [Kiatra/BlizzMove#103]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

I have installed the addon "Soulshape Journal" https://www.curseforge.com/wow/addons/soulshape-journal
It ads a tab called "Soulshapes" to the collection frame. When I click the tab, I cant move the frame around.

Can you make a Blizzmove plugin for that addon as you did with the "Rematch" addon?

### Steps to reproduce.

*

### Expected behavior.

*

**Comment by Numynum** [comment]
I'll take a look to see how much work it'd be.

**Comment by Numynum** [comment]
you can download it from here soon™: https://www.curseforge.com/wow/addons/blizzmove-plugin-soulshape-journal
(new projects can take a few hours, or a few days, before they get approved and show up for everyone)
