### ISSUE TITLE
Map regions no longer clickable when map is scaled up / down

### ISSUE THREAD

**Issue by JakobDylanC** [Kiatra/BlizzMove#105]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Map regions no longer clickable when map is scaled up / down

### Steps to reproduce.

1. Open map, zoom out
2. Hold ctrl and scroll up / down to scale the window
3. Try to click a region

### Expected behavior.

Regions should always be clickable

**Comment by Numynum** [comment]
Hi, unfortunately, this is a known issue, that only blizzard can (very easily) fix..
https://github.com/Stanzilla/WoWUIBugs/issues/338 for reference
