### ISSUE TITLE
[Bug Report] Pop up when I accidentally clicked on the frame of my quest window

### ISSUE THREAD

**Issue by Barleduq** [Kiatra/BlizzMove#106]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

I can't tell if this has been reported; I didn't see anything referencing the addon QuestGuru.  I just want to follow directions.  I did not disable all my addons. I haven't had anything pop up before like this.  My apologies if this is a total waste of time without that, and please feel free to delete this if it's useless without the troubleshooting.

I accidentally clicked the frame of the quest window instead of the accept button on the quest from Noriko the All-Remembering. After I copied the text from the popup, the quest pane went blank - the portrait icon is still there, but there are now no text in the frame and no text on the buttons, and the buttons don't work - not even the X close button in the upper right. Escape key did close it, and when I clicked again the quest is "For the Love of Others."  I have no idea if any of this is relevant, but I'm giving info to identify where I am. 

I *have* been getting errors for quest guru, mostly referencing quest guru sounds, which is a separate addon installed by quest guru.  I have quest guru sounds turned off, and still get the errors.  However, everything is still working, and I can't figure out what's wrong or how to repeat it. It doesn't happen with every quest activity, even the ones that trigger noise.  

### Steps to reproduce.

Click on the quest frame instead of a button. 

### Expected behavior.

My expectation is that I would have to try to move the pane before getting an error.  I wasn't moving the mouse when I clicked on the frame by accident. 

### Errors

```lua
Here is the text of the pop-up: 

BlizzMove: The frame you just moved (QuestFrame) is probably in a broken state, possibly because of other addons. Copy the text from this popup window, and report it to the addon author.

Bad anchor connections for "QuestFrame":


"QuestFramePortrait" is outside anchor family, but referenced by "QuestNpcNameFrame" (created in "Interface/SharedXML/SharedUIPanelTemplates.xml:997", and "Interface/FrameXML/QuestFrame.xml:52" respectively)

"QuestGuru" is outside anchor family, but referenced by "QuestGuruDetailScrollFrame" (created in "Interface/AddOns/QuestGuru/QuestGuru.xml:85", and "Interface/AddOns/QuestGuru/QuestGuru.xml:413" respectively)

end of pasted text.
```

**Comment by Numynum** [comment]
Hi, this is something that'll have to be fixed in QuestGuru
unfortunately there isn't really a way to tell the game to only do something when dragging, but not when clicking (not unless you want a laggy feeling)
so you getting an error when clicking, is not fixable 
there's 2 options left, you can either disable the quest guru addon; or in `/bm`, disable the quest frame from moving 
unless/until the dev fixes the anchor connection issue
