### ISSUE TITLE
[Bug Report] Maximized addon Mapster is out of frame

### ISSUE THREAD

**Issue by tealkami** [Kiatra/BlizzMove#109]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When I missclick that maximize button on mapster, it is out of frame (top left) so the top corner of Mapster is unclickable to go back to small window.
Did test it with or without Blizzmove , without Blizzmove it was in the display frame
and I did write bug report on Mapster addon too

### Steps to reproduce.

download Mapster, go ingame with Mapster+BlizzMove, and click that arrow button to maximize the map window

### Expected behavior.

Maximized Mapster(while using Blizzmove) shouldn't be out of frame 
:D (I just find this bug report formating little bit silly)

**Comment by tealkami** [comment]
I did some testing, and in Option => Addons=> List of Frames => You turn off **WorldMapFrame** it make the Map window unmovable(even with Mapster on), but if I disable BlizzMove and have only Mapster, I can move map window/frame. So my guess is that BlizzMove and Mapster use code with the **WorldMapFrame**, but BlizzMove take priority above Mapster, which make a problem for maximized Mapster.

Suggestion : What about add something like : "if addon Mapster is detected, **WorldMapFrame** will be ignored by BlizzMove", so only Mapster will control **WorldMapFrame**

**Comment by Numynum** [comment]
tried reloading UI after disabling WorldMapFrame?
BlizzMove should do nothing with disabled frames after reloading UI

**Comment by tealkami** [comment]
Yes, after relog Mapster make the Map movable, and when maximized it is not out of frame.

So can you add something like : "If Mapster addon is detect, turn off **WorldMapFrame**; if not detected Turn on it back" ?

**Comment by Numynum** [comment]
thanks for the confirmation 👌 

we're not planning on adding workarounds and exceptions for other addons into blizzmove, as that'd be a fulltime job 🙂

**Comment by tealkami** [comment]
Really ? I did imagine that it is like 1 line of **short** code, like was that [Altoholic debacle](https://user-images.githubusercontent.com/37823216/103165741-36050380-47d0-11eb-9c38-a35032d4dc15.png)
hmmm Can you do it at least this one time, please ?
Anyway I did try :)
