### ISSUE TITLE
[Bug Report] Taintless issue -Getattribute hooksecurefunc

### ISSUE THREAD

**Issue by EvilMerc** [Kiatra/BlizzMove#111]
### What game version did the bug occur in?

Wrath of the Lich King Classic

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Taintless issue - GetAttribute is not a function

Message: [string "Interface/AddOns/BlizzMove/TaintLess.xml:<S..."]:77: hooksecurefunc(): GetAttribute is not a function
Time: Thu Jun 22 10:42:31 2023
Count: 1
Stack: [string "Interface/AddOns/BlizzMove/TaintLess.xml:<S..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "Interface/AddOns/BlizzMove/TaintLess.xml:<Scripts>"]:77: in main chunk

Locals: 

### Steps to reproduce.

Load addons:
BugSack
BugGrabber
BlizzMove

Log in/reload UI.

### Expected behavior.

Expected: Error not received.

Actual: Error received.  Seems no functionality experienced.

**Comment by Numynum** [comment]
fixed
