### ISSUE TITLE
UI Frame's Saved Positions Slightly Off When Scaled Above or Below 100%

### ISSUE THREAD

**Issue by V1rtuou5** [Kiatra/BlizzMove#114]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Positions for UI frames are not being correctly saved upon /reload or relog in exact location when the scale of said frame is not 100% (default) even with "Remember permanently" setting enabled.

### Steps to reproduce.

Change the scale of UI frame to anything other than default and it will not be in same position upon /reload or character relog.

### Expected behavior.

Position of UI frame to be saved at exact last known location upon /reload or relog.

**Comment by Numynum** [comment]
should work better in the next update
keep in mind that positions can still shift slightly due to rounding errors, especially if you don't use pixel perfect UI scales
