### ISSUE TITLE
[Bug Report] Doesn't work after 3.5.20

### ISSUE THREAD

**Issue by GregoryGH** [Kiatra/BlizzMove#115]
### What game version did the bug occur in?

Vanilla Classic

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Not working at all. 3.5.19 works fine. SoD

### Steps to reproduce.

none

### Expected behavior.

working

### Errors

```lua
none
```

**Comment by Numynum** [comment]
it's working fine for me, got any more info?

**Comment by GregoryGH** [comment]
Well, just tried .20 again and now it works. No idea what happened.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 10 янв. 2024 г. в 16:20, MarkW ***@***.***>:
