### ISSUE TITLE
[Feature Request] Support for Manuscripts Journal

### ISSUE THREAD

**Issue by Konsafloof** [Kiatra/BlizzMove#116]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Id like to suggest support for [Manuscripts Journal](https://www.curseforge.com/wow/addons/manuscripts-journal) since you've added support for Soulshape Journal and Rematch.

### Steps to reproduce.

.

### Expected behavior.

.

**Comment by Numynum** [comment]
I've updated blizzmove to allow dragging the title bar, which should be compatible with most collection journal extending addons

you can download a dedicated Manuscripts Journal plugin here: https://github.com/NumyAddon/BlizzMovePlugin_ManuscriptsJournal/releases (once Curseforge approves the project in a day or two, you can download it [here](https://legacy.curseforge.com/wow/addons/blizzmove-plugin-manuscripts-journal) as well)
