### ISSUE TITLE
[Bug Report] Not able to move collections frame with Rarity and Blizzmove active

### ISSUE THREAD

**Issue by Konsafloof** [Kiatra/BlizzMove#117]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Not able to move Collections frame with Rarity and Blizzmove active
edit #1 for some reason [enabling Bagnon fixes it](https://youtu.be/uJ1-yiNW5Pc) ,Im not sure why
edit #2 also seem a few extra addons fix it, Im gonna be honest I dont know why and Im sorry

### Steps to reproduce.

Enable both Rarity and Blizzmove then try to move Collections frame
[Video link of what happens](https://youtu.be/m1RFhXmChfw)

### Expected behavior.

Having both Rarity and Blizzmove active and still be able to move Collections frame

### Errors

```lua
Ive attached a video link, no error messages
```

**Comment by Numynum** [comment]
this was an interesting puzzle 🙂
it's caused by a peculiar detail in blizzard's logic, combined with the Rarity addon, loading the Blizzard_Collections "addon" at the exact time when BlizzMove would be unaware of it, so for us, it's as if the collection journal was never loaded

should be fixed in the next update

**Comment by Konsafloof** [comment]
Rarity still does affect Manuscripts Journal from being moved oddly

**Comment by Numynum** [comment]
created an issue there https://github.com/NumyAddon/BlizzMovePlugin_ManuscriptsJournal/issues/1
probably easy enough to fix
