### ISSUE TITLE
[Bug Report] v3.5.24 introduces a conflict with AceHook

### ISSUE THREAD

**Issue by tflo** [Kiatra/BlizzMove#118]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Does not occur with v3.5.23.

Note that the addon mentioned in the error log (Accountant_Classic) is irrelevant, as it is just the provider of the AceHook library (alphabetically first in the loading order).

### Steps to reproduce.

Right after login/reload.

I _had to_ tick the "I have tried to reproduce the bug with no other addons loaded" because it is required to post the ticket(!). But actually this is a conflict with another addon (AceHook), so this does not apply.

### Expected behavior.

Should not conflict.

### Errors

```lua
1x .../Accountant_Classic/Libs/AceHook-3.0-9/AceHook-3.0.lua:180: Attempting to rehook already active hook GetBagsShown.
[string "=[C]"]: ?
[string "@Accountant_Classic/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:180: in function <.../Accountant_Classic/Libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Accountant_Classic/Libs/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@BlizzMove/BlizzMove.lua"]:1314: in function `?'
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Accountant_Classic/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ccountant_Classic/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "Attempting to rehook already active hook GetBagsShown."
```

**Comment by Numynum** [comment]
and this does not happen with no other addons enabled, or with an older blizzmove version?

**Comment by tflo** [comment]
As said, does not occur with v3.5.23. I did not test with older versions before that, but I've never seen the error before, IIRC, and I'm using BM for quite a few years.

If I reload with a minimal addon set (or with only BM and BugSack), the error does not occur. But I guess this is due to the absence of AceHook…

**Comment by tflo** [comment]
I have to correct myself: If I load only with BM and BugSack and Accountant_Classic (to provide the Ace lib), the error does not occur. So something more must be involved…

**Comment by Numynum** [comment]
And this is classic yes? (since you selected retail 🙂)
we'll take a look

**Comment by tflo** [comment]
No, this is Retail. I don't play Classic.

**Comment by tflo** [comment]
Accountant_Classic is a Retail addon, despite the name.

**Comment by tflo** [comment]
I now reloaded with BM, BugSack, and BattlePetCount as the AceHook lib provider, and I get the error again. Reproducible.

**Comment by tflo** [comment]
And the AceHook versions are the same:

```lua
-- @release $Id: AceHook-3.0.lua 1284 2022-09-25 09:15:30Z nevcairiel $
```

Weird…

**Comment by tflo** [comment]
I installed now Ace3-Release-r1320 separately, and the error does not occur.

**Comment by tflo** [comment]
I just verified again with BM v3.5.23 (because I couldn't believe it), but the error does definitely not occur, even with one of my regular addon sets.

**Comment by tflo** [comment]
I hope that bug reports by other people will provide a better clue what is going on here, but – for the moment – rolling back to 3.5.23 seems a reasonable thing for me.

**Comment by Numynum** [comment]
I'll have time to take a look later today probably, but if BM + BattlePetCount is reproduceable on my end, it should be easy enough to debug and fix 👍 
(it's not caused by AceHook, but some other quirk, but I'll have to double-check what exactly is happening)

**Comment by tflo** [comment]
> if BM + BattlePetCount is reproduceable

It seems to be reproducible, yes. It's [BattlePetCountNG](https://www.curseforge.com/wow/addons/battlepetcount-ng).

**Comment by tflo** [comment]
More precisely:

BM 3.5.24 alone: No error
BM 3.5.24 + Accountant_Classic: No error
BM 3.5.24 + BattlePetCountNG: Error with BattlePetCountNG's AceHook as source
BM 3.5.24 + Accountant_Classic + BattlePetCountNG: Error with Accountant_Classic's AceHook as source

**Comment by raysmith59** [comment]
I've had this error with 3 addons so far: Better Wardrobe and Transmog, BigDebuffs and now BlizzMove, as I disable them more keep showing up... I don't use BattlePetCountNG so something else is contributing to this for me at least.  I'm continuing to test on my end, will follow up.

**Comment by raysmith59** [comment]
Disabling BlizzMove fixed the errors in the other two add-ons I mentioned above.  Seeing if I can figure out the conflict but I have a lot of add-ons, no promises...

**Comment by tflo** [comment]
@raysmith59, for you it's also only with Blizz Move 3.5.24, or with the previous version (3.5.23) too?

**Comment by Numynum** [comment]
just go with the previous version of blizzmove for now, and it should be fine

**Comment by raysmith59** [comment]
Just 3.5.24, 3.5.23 has no error.

**Comment by raysmith59** [comment]
Unfortunately couldn't figure out the specific conflict, tested BlizzMove with batches of other add-ons and didn't get the error so I figure it has to be a 3+ addon conflict... will keep testing for a bit.

**Comment by Numynum** [comment]
[v3.5.25](https://github.com/Kiatra/BlizzMove/releases/tag/v3.5.25) should be available on CF soon, and fixes the problem

for anyone curious, the issues are caused when an addon using AceEvent, is loaded before BlizzMove, and registers the ADDON_LOADED event
this causes our code to run twice, and AceHook to complain that it's already done its job

thanks for the debugging on your ends

**Comment by raysmith59** [comment]
Glad to hear it, I had at least a 4-way addon conflict causing my issue and I hadn't figured out the specific combo yet.

**Comment by tflo** [comment]
Oh, that was fast. Thanks 😃

**Comment by raysmith59** [comment]
Confirmed that 3.5.25 works for me.
