### ISSUE TITLE
[Bug Report] Classic Era Update 1.15.1 - Leave Vehicle Button while flying not moveable

### ISSUE THREAD

**Issue by maximus210793** [Kiatra/BlizzMove#121]
### What game version did the bug occur in?

Vanilla Classic

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Leave Vehicle Button while flying not moveable

### Steps to reproduce.

Book a gryphon flight and try to move the leave vehicle button, it won't work.

### Expected behavior.

Button should be moveable like every other blizzard ui element

### Errors

```lua
[Bug Report] Classic Era Update 1.15.1 - Leave Vehicle Button while flying not moveable
```

**Comment by Numynum** [comment]
duplicate https://github.com/Kiatra/BlizzMove/issues/123
