### ISSUE TITLE
[Bug Report] <CharacterFrame>

### ISSUE THREAD

**Issue by DannyHammers** [Kiatra/BlizzMove#124]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When trying to move the character sheet window while the "equiprecommendedgear" addon is active the character sheet window removes everything but the player model.

### Steps to reproduce.

open character window
attempt to move
window disappears other than player model which is also immobilized 

### Expected behavior.

I was expecting to move the character sheet

### Errors

```lua
Bad anchor connections for "CharacterFrame":


"UIParent" is outside anchor family, but referenced by "UIParent.1d44735de10" (created in "Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.xml:3", and "Interface/AddOns/EquipRecommendedGear/Core.lua:104" respectively)
```

**Comment by Numynum** [comment]
it's caused by the other addon, see https://github.com/Sluimerstand/EquipRecommendedGear/issues/10

**Comment by Sluimerstand** [comment]
@DannyHammers With the advice of Numynum this issue is now resolved in Equip Recommended Gear. The new version should be out soon on Curse/Wago. :)
