### ISSUE TITLE
[Bug Report] actionbutton taint

### ISSUE THREAD

**Issue by Nefram56** [Kiatra/BlizzMove#129]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

I thought it had something to do with modifiers shift, alt and ctrl but it keeps happening until reload and seems to fix it. I haven't had it pop up after reload .

### Steps to reproduce.

use any ability with keybinds

### Expected behavior.

Ability to activate

### Errors

```lua
5x [ADDON_ACTION_FORBIDDEN] AddOn 'BlizzMove' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseAction'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:342: in function `handler'
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:667: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:649>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:681: in function <...ddOns/Blizzard_FrameXML/Mainline/SecureTemplates.lua:674>
[string "@Blizzard_FrameXML/Mainline/SecureTemplates.lua"]:723: in function `SecureActionButton_OnClick'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:135: in function `ActionButtonDown'
[string "ACTIONBUTTON12"]:2: in function <[string "ACTIONBUTTON12"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
```

**Comment by Numynum** [comment]
Have you confirmed this happens with all other addons disabled, and stops happening when blizzmove is disabled?
cause this looks like a situation where blizzmove gets blamed for another addon's bug
