### ISSUE TITLE
[Bug Report] BlizzMove breaks Hero Talent selection screen

### ISSUE THREAD

**Issue by KyrosKrane** [Kiatra/BlizzMove#131]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When first selecting hero talents, you can click outside the hero talent area (in the open world frame) which closes the hero talent window. This causes a lua error. Reopening the hero talent frame corrupts the display.

Tested with BlizzMove v3.5.35. I note that bug #130 seems to be the same thing; however, this is still occurring after that fix was released.

![image](https://github.com/user-attachments/assets/797d6b0c-1f5e-4060-ac64-a3164dc5213a)

### Steps to reproduce.

1) Load only BlizzMove, Buggrabber, and Bugsack.
2) Log in to a toon that is eligible to select hero talents, but has not yet chosen one. (I have not yet tested with a toon that has selected a hero talent tree already.)
3) Open the talent selection frame.
4) Click the hero talents circle at the center of the frame to open the hero talent selection screen.
5) Click in the open game world (not on any UI element).
6) The bug occurs.

### Expected behavior.

The bug does not occur. The window opens as normal.

### Errors

```lua
2x ...pells/ClassTalents/Blizzard_HeroTalentsContainer.lua:510: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: Button:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:510: in function `UpdateHeroTalentButtonPosition'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:472: in function `UpdateContainerVisibility'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:562: in function <...pells/ClassTalents/Blizzard_HeroTalentsContainer.lua:558>
[string "=(tail call)"]: ?
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua"]:52: in function <...ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua:44>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua"]:293: in function <...ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua:292>
[string "=(tail call)"]: ?

Locals:
(*temporary) = Button {
 BorderSheen = Texture {
 }
 Shadow = Texture {
 }
 spendTextShadows = <table> {
 }
 StateBorder = Texture {
 }
 SpendTextShadow2 = FontString {
 }
 Glow = Texture {
 }
 ArtSet = <table> {
 }
 SpendTextShadow4 = FontString {
 }
 deselectSound = 207762
 sheenMaskAtlas = "talents-node-choice-sheenmask"
 selectSound = 207763
 frameLevelOffset = 0
 SpendTextShadow1 = FontString {
 }
 Icon2 = Texture {
 }
 IconSplitMask = MaskTexture {
 }
 SpendText = FontString {
 }
 isGhosted = false
 IconMask = MaskTexture {
 }
 Icon = Texture {
 }
 SpendTextShadow3 = FontString {
 }
 visualState = 7
 talentSelections = <table> {
 }
 actionBarStatus = 1
 BorderSheenMask = MaskTexture {
 }
 nodeInfo = <table> {
 }
 artSet = <table> {
 }
 talentFrame = Frame {
 }
 tooltipBackdropStyle = <table> {
 }
 StateBorderHover = Texture {
 }
 nodeID = 95073
 DisabledOverlayMask = MaskTexture {
 }
 SelectableIcon = Texture {
 }
 Ghost = Texture {
 }
 DisabledOverlay = Texture {
 }
 SelectableGlow = Texture {
 }
 Icon2Mask = MaskTexture {
 }
 SearchIcon = Frame {
 }
}
(*temporary) = "TOP"
(*temporary) = Frame {
}
```

**Comment by Numynum** [comment]
And when just closing it with ESC?

**Comment by Numynum** [comment]
please try v3.5.36, and if that doesn't work for you, I'll have to go with plan B, which ain't pretty 🙈

**Comment by KyrosKrane** [comment]
I already picked a hero talent on that toon; not sure if that changes things. 

I retested with .35. Opening the hero window, clicking in the open world, still generated the error. I then updated to .36. This time it didn't cause the error. If you want, you can keep this open until I level another toon to retest, but I'm thinking it's safe to close. Up to you.

**Comment by Numynum** [comment]
Tbh, if it does still break on initial selection, I can live with that ^^
