### ISSUE TITLE
Main map is bugged with this addon. 

### ISSUE THREAD

**Issue by smtips01** [Kiatra/BlizzMove#134]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Main map is bugged with this addon. In full screen, it is pushed off to the left with big black area on the right and below it and cannot access menus for the map such as add a pin.

### Steps to reproduce.

Disable all addons, reenable only the blizmove debug and addon. 

### Expected behavior.

The map should display normally like it does with no addons turned on.

**Comment by smtips01** [comment]
Seems to be resolved with a recent update

**Comment by Numynum** [comment]
Oh yeah, forgot to update the issue 🙂
