### ISSUE TITLE
Blizzard_PlayerSpells > PlayerSpellsFrame  is causing talent frame to be zoomed in upon opening.

### ISSUE THREAD

**Issue by V1rtuou5** [Kiatra/BlizzMove#139]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Zoomed in talents page upon opening. Can be fixed by either moving mousewheel, choosing a different talent loadout, or completely disabling "PlayerSpellsFrame"
![image](https://github.com/user-attachments/assets/350150a1-2ac2-4a53-ae84-e3c7a1b73b6a)

### Steps to reproduce.

Open Talents (N) with PlayerSpellsFrame turned on.

### Expected behavior.

Zoomed out upon opening Talents.

**Comment by Numynum** [comment]
hi, try the `Reset Permanent Scales` button
![image](https://github.com/user-attachments/assets/d7d0e5a2-1b1d-4a73-b83d-bcfc286ff06d)

**Comment by V1rtuou5** [comment]
Thank you! This seems to have fixed it.
