### ISSUE TITLE
Save position of frames (after reload/relogs)

### ISSUE THREAD

**Issue by Chironeyes** [Kiatra/BlizzMove#26]
It's possible to add a save frame position system ? 
Because each time I close the game or use /reload command frames are reset =/

Thanks for all and thanks for BlizzMove <3

**Comment by Numynum** [comment]
that idea comes up every now and then, but for now it probably won't happen
saving the positions gives a ton of glitchy/buggy behaviour that we want to avoid

it might happen someday though

**Comment by GeekToBe1** [comment]
The addon MovableBags for classic has included commands like **/bags lock** and **/bags unlock** and it works perfectly to save bag frames positions in all cases. 

It will be nice if that can help to studdy the case and make it possible :)

**MoveableBags :**
https://www.curseforge.com/wow/addons/movablebags/files

Does this can help ?

**Comment by Numynum** [comment]
I had a look, and the way that addon handles saving frames is not really scalable; you can do it for one or two frames (like bags), but it's not really nice for the tons of frames we support with BlizzMove
cheers for the suggestion though

**Comment by Voxxel** [comment]
I use an addon called MoveTalkingHead for years now and it has just as simply usage as your addon. Just grab the frame and release -- but it automatically saves positions. Could you see if maybe you can use its method to store frame positions?

https://www.curseforge.com/wow/addons/movetalkinghead

**Comment by Numynum** [comment]
thanks for trying to help, but addons which only move and save 1 or only a few frames probably won't be very helpful to us :)
the only challenge we have to solve, is preventing glitches; and a good way to reset the position (we have some good ideas for both problems)

this request is something we'd like to do (if we can do it without too many glitches) but don't count on it being very soon :)

**Comment by Bruncky** [comment]
[MoveAnything](https://www.curseforge.com/wow/addons/Move-Anything) moves...well, anything and saves every position.

Like @Numynum is saying, however, it is **very** glitchy. It works for most things for a while, but for some reason every now and then it starts glitching hard and I end up having to disable it. I don't know if it conflicts with some other addon or if saving positions is inherently glitchy, but the fact is that it's hard to get working flawlessly. If it's a matter of it being inherently glitchy, then focusing on this might really be a waste of time. At least BlizzMove saves positions for the current session, so it's not all bad!

**Comment by KoborOld** [comment]
Shadowland is coming, with current state MoveAnything is not working, that will be a hard time to play Wow on wider screens.
Do you think MA addon codes might help the glitches on permanent position saves?

**Comment by KoborOld** [comment]
https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

This article is helping?

**Comment by Numynum** [comment]
@KoborOld MA is the one that's glitching all over, so their code might only help in the sense as to tell us what not to do ;)
and that article doesn't help much for BlizzMove, as for us nothing much changes; but cheers for trying to help

**Comment by Numynum** [comment]
an alpha version (v3.0.2-alpha) will be available on curse/twitch client soon, which lets you test an early version of this feature

type `/bm` to open the config, and chose `Permanent` in the dropdown
expect many bugs though

feel free to report issues you find, but they are quite low priority, unless they also happen when using the default options

**Comment by Numynum** [comment]
this option is now available in the latest release version
closing this issue; if you experience problems, please create new issues :)
