### ISSUE TITLE
pressing SHIFT+Click does not reset a moved frame.

### ISSUE THREAD

**Issue by panoplybez** [Kiatra/BlizzMove#35]
So I just installed BlizzMove, and after moving a frame, I get the message 'frame has moved, press SHIFT+Click to reset it', but when I do a SHIFT+Click, nothing happens. I've tried clicking inside the frame, outside it, on its top bar, but nothing resets it. Is that functionality broken?

**Comment by zaCade** [comment]
Whats the frame in question on which its not working?
Could be the way i made the reset that doesn't work on that frame.
But ill need to know the what the frame is so i can look if thats the case, and possibly for a solution.

**Comment by panoplybez** [comment]
I tried it on 2 of them - I tried it on the blizzard menu (hit ESC), and also on the Interface window (system menu > Interface button). Thx.

**Comment by panoplybez** [comment]
did more testing!

does not reset when shift clicked:
Game Menu
Help
System
Interface
Key Bindings
Addons list

does not move at all:
Shop

**Comment by Numynum** [comment]
Thanks for the testing
First off all, the shop cannot be touched by any addon, so we cannot force it to move :/
We'll look into the other frames and see what can be done :)

just to confirm, are you using any ui replacement addons like elvui, or addons that change those specific frames in any way?

**Comment by panoplybez** [comment]
Thanks for looking into it! 

I am using elvui, but I do not apply the skins to any of the blizzard frames. So all of these things I am opening are the original wow look&feel. I only skin the Objectives/Chat/Bars with Elvui. 

Side note - I noticed that the description of the addon says there's an issue where position is not retained after a reload/logout. However, in my testing, it is retained. But that can be an option? I was hoping to use a reload to reset where everything was, but it seems that has been fixed heh. If its an option, we can choose to have it reset or not? Just a thought.

**Comment by Numynum** [comment]
there might be something wrong with your layout settings already then, because resetting by reloading and shift clicking essentially work the same way
deleting your ui-layout file should fix it; will give the location in a few mins if you don't know where it is, busy atm :)

**Comment by panoplybez** [comment]
Sorry I have to keep amending my comments he.

So the reset on reload of UI works on the other frames. but its not working on the above ones heh. So you can move the above, but then not reset them.

**Comment by Numynum** [comment]
so yeah, if you still can't reset after deleting the file in `{game instal directory}\_retail_\WTF\Account\{number}#1\{server}}\{character}\layout-local.txt`, let us know, and we'll look into it :)
addons sometimes tell the game that a specific frame shouldn't be reset, and that sticks around even after you uninstal/disable the addon, and it's stored in that file

**Comment by panoplybez** [comment]
Sure thank you, will try. Disabling/enabling the addon did reset it. But it also did seem a problem for only those few frames mentioned above.

**Comment by ExoKalork** [comment]
Hi ! I'm having the same issue. I can move and resize frames just fine, but both CTRL+click or Shift+Clic aren't working.
I've tried on almost every ingame window and it's the same problem for all of them.
Removing the layout-locale.txt file did reset everything, but it does not allow me to reset ingame again.
No error in BugSack or anything, just nothing happening.

**Comment by Numynum** [comment]
@ExoKalork did you try disabling all addons apart from blizzmove, remove layout-locale, and try again
for example with the character frame?

are you saying that CTRL+right-click doesn't reset the size of the frames either?

just to make sure, you're using right-click for reset, not left-click?

**Comment by Numynum** [comment]
this is fixed in the next update (should be downloadable soon™)
