### ISSUE TITLE
Feature request: reset position on frame close

### ISSUE THREAD

**Issue by Saxayone** [Kiatra/BlizzMove#43]
Personally I loved the functionality of the an older version which would just reset windows on closing them rather than keeping them constant until reload/logoff.
Was using the outdated version until pre-patch because of it so I was wondering if there is any way you could implement an option to toggle that would just not save the frame location?
Sometimes I just prefer that method of handling it when dealing with a lot of things at once.

Looking at it I'd think it would just be within OnMouseUp?
if toggle then
    frameData.storage.dragged = false;
else
    frameData.storage.dragPoints = GetFramePoints(frame);
    frameData.storage.dragged = true;
end

**Comment by Numynum** [comment]
sounds relatively easy to implement, will look at it later :)

**Comment by Numynum** [comment]
an alpha version (v3.0.2-alpha) will be available on curse/twitch client soon, which lets you test an early version of this feature

type `/bm` to open the config, and chose `Do not remember` in the dropdown

switching between the options should be seamless, and not require any reloads

**Comment by Numynum** [comment]
this is now available in the latest stable version, downloadable through the curse/twitch client soon
