### ISSUE TITLE
Remember Permanently

### ISSUE THREAD

**Issue by Palonblade** [Kiatra/BlizzMove#45]
I have set my settings to "Remember permanently" and it seems to work on some toons and not others. Specifically the "Game Menu". On some toons it uses the saved position, on others it doesn't. On the ones it doesn't, it remembers until I log out and back in.

**Comment by Numynum** [comment]
hey, can you type `/dump GameMenuFrame:IsUserPlaced()` on a character than works, and one that doesn't work; and tell me the results?
we can look into fixing it, but as the popup says, expect bugs, as remembering permanently is generally buggy :)

**Comment by Palonblade** [comment]
True for the ones working false for the ones not working. It appears that for the ones working that there are entries for "Frame: GameMenuFrame" in the character specific file layout-local.txt while the ones not working there are no "Frame: GameMenuFrame" entries if that helps.

**Comment by Palonblade** [comment]
Do you need any additional information?

**Comment by Numynum** [comment]
hi, I think this should be enough to reproduce and later fix it
if you happen to notice this with other frames, please let us know :)

I haven't had time to look into it yet, and (to set expectations) I don't think I'll find the time until after SL has launched
and as mentioned before, saving permanently seems rather buggy with every addon that tries it, so we may never find a great solution that works for all frames :/

**Comment by Numynum** [comment]
we finally put some more time and effort into the remembering permanently feature, and I believe all of this _should_ be resolved now :)
