### ISSUE TITLE
Failure messages on login

### ISSUE THREAD

**Issue by panoplybez** [Kiatra/BlizzMove#52]
When I log in, I see 2 errors printed to chat:

BlizzMove: Failed to make frame movable: PVPMatchResults 
BlizzMove: Failed to make frame movable: ChannelFrame

**Comment by Numynum** [comment]
Hi, do you play on classic, or retail?

**Comment by zaCade** [comment]
This happend due to an accidental oversight when i added something in v3.0.8, should be fixed now.
