### ISSUE TITLE
Cannot select torgast powers

### ISSUE THREAD

**Issue by nivthefox** [Kiatra/BlizzMove#54]
When in Torgast, I have to disable BlizzMove or I cannot view Torgast power descriptions or make a selection.

**Comment by Numynum** [comment]
this seems to be an issue with a different addon, or the interaction between BlizzMove and that addon
I didn't have issues for a long time, then a few weeks ago I started getting issues (BlizzMove hadn't been updated or changed though)
and now after the 9.0.5 patch I'm not having any issues anymore myself
