### ISSUE TITLE
Breath Bar

### ISSUE THREAD

**Issue by Mostfamous** [Kiatra/BlizzMove#57]
please add "MirrorTimer1" Breathbar to Frames.lua

 Thx and greetings

**Comment by Numynum** [comment]
I have no idea what this frame is, can you post a screenshot or something?

**Comment by Kiatra** [comment]
Its the frame that shows how much Breath is left when the character is underwater :D
It's really MirrorTimer1, I just checked.

**Comment by Numynum** [comment]
there's currently no plans of adding these kinds of frames to blizzmove, since it falls outside of the concept for this addon
as an alternative you can use elvui, moveanything, or create your own blizzmove plugin (if you're handy with lua) to move these frames
