### ISSUE TITLE
Add objective tracker to items that can be moved

### ISSUE THREAD

**Issue by EnserNG** [Kiatra/BlizzMove#58]
Being able to move and save the position of the quest/objective tracker would be awesome.  Hope that you will consider including it!

**Comment by Numynum** [comment]
this isn't something we'll add in the main addon; I will probably make a plugin for this though, if/when I do, I'll link it here

**Comment by EnserNG** [comment]
Thank you for considering it - that would be awesome, if you have the time and inclination.

**Comment by Numynum** [comment]
https://www.curseforge.com/wow/addons/blizzmove-plugin-questtracker should be available in a day or so (new projects sometimes take a while to show up)
