### ISSUE TITLE
When I move the windows, I get this error

### ISSUE THREAD

**Issue by hn0123** [Kiatra/BlizzMove#60]
Global variable CanIMogIt tainted by BlizzMove - Interface\AddOns\CanIMogIt\core.lua:5
Execution tainted by BlizzMove while reading CanIMogIt - Interface\AddOns\CanIMogIt\code.lua:479 _GetAppearances()
   Interface\AddOns\CanIMogIt\code.lua:502
   Interface\FrameXML\StaticPopup.lua:4989 StaticPopup_OnClick()
An action was blocked because of taint from BlizzMove - LeaveClub()
  Interface\FrameXML\StaticPopup.lua:2358 OnAccept()
  Interface\FrameXML\StaticPopup.lua:5021 StaticPopup_OnClick()
  StaticPopup1Button1:OnClick()

**Comment by Numynum** [comment]
try installing https://www.townlong-yak.com/addons/taintless, and let us know if that helps please 👌

**Comment by hn0123** [comment]
> 尝试安装https://www.townlong-yak.com/addons/taintless，让我们知道是否有帮助，请

This is the new log only blizzmove and taintless

**Comment by hn0123** [comment]
> try installing https://www.townlong-yak.com/addons/taintless, and let us know if that helps please

This is the new log only blizzmove and taintless.
 Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by BlizzMove - Interface\SharedXML\UIDropDownMenu.lua:37
     securecall()
     Interface\SharedXML\UIDropDownMenu.lua:73 UIDropDownMenu_Initialize()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1440 CommunitiesFrame:UpdateStreamDropDown()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1406 CommunitiesFrame:SelectStream()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1199 CommunitiesFrame:OnClubSelected()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:449 CommunitiesFrame:UpdateSelectedClubInfo()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:440 CommunitiesFrame:SelectClub()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:418 CommunitiesFrame:UpdateClubSelection()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:146
     CommunitiesFrame:Show()
     Interface\FrameXML\UIParent.lua:2915 <unnamed>:SetUIPanel()
     Interface\FrameXML\UIParent.lua:2760 <unnamed>:ShowUIPanel()
     Interface\FrameXML\UIParent.lua:2628
     <unnamed>:SetAttribute()
     Interface\FrameXML\UIParent.lua:3473 ShowUIPanel()
     Interface\FrameXML\UIParent.lua:3434 ToggleFrame()
     Interface\FrameXML\UIParent.lua:1068 ToggleCommunitiesFrame()
     Interface\FrameXML\UIParent.lua:922 ToggleGuildFrame()
     TOGGLEGUILDTAB:1
 Execution tainted by BlizzMove while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\SharedXML\UIDropDownMenu.lua:851 UIDropDownMenu_GetSelectedID()
     Interface\SharedXML\UIDropDownMenu.lua:533 UIDropDownMenu_AddButton()
     Interface\FrameXML\UnitPopup.lua:835 UnitPopup_AddDropDownButton()
     Interface\FrameXML\UnitPopup.lua:622 UnitPopup_ShowMenu()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1454 initFunction()
     Interface\SharedXML\UIDropDownMenu.lua:78 UIDropDownMenu_Initialize()
     Interface\SharedXML\UIDropDownMenu.lua:1055 ToggleDropDownMenu()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:704 <unnamed>:OnClubMemberButtonClicked()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1149
 Interface\FrameXML\StaticPopup.lua:4989 StaticPopup_OnClick()
 An action was blocked because of taint from BlizzMove - GuildLeave()
     Interface\FrameXML\StaticPopup.lua:845 OnAccept()
     Interface\FrameXML\StaticPopup.lua:5021 StaticPopup_OnClick()
     StaticPopup1Button1:OnClick()
 Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by BlizzMove - Interface\SharedXML\UIDropDownMenu.lua:37
     securecall()
     Interface\SharedXML\UIDropDownMenu.lua:73 UIDropDownMenu_Initialize()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1440 CommunitiesFrame:CommunitiesFrame:()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1406 CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1199 CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:449 CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:440 CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesF()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:418 CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesF()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:146
     CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesFrame:CommunitiesF()
     Interface\FrameXML\UIParent.lua:2915 <unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:()
     Interface\FrameXML\UIParent.lua:2760 <unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:()
     Interface\FrameXML\UIParent.lua:2628
     <unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:<unnamed>:()
     Interface\FrameXML\UIParent.lua:3473 ShowUIPanel()
     Interface\FrameXML\UIParent.lua:3434 ToggleFrame()
     Interface\FrameXML\UIParent.lua:1068 ToggleCommunitiesFrame()
     Interface\FrameXML\UIParent.lua:922 ToggleGuildFrame()
     TOGGLEGUILDTAB:1
 Execution tainted by BlizzMove while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\SharedXML\UIDropDownMenu.lua:851 UIDropDownMenu_GetSelectedID()
     Interface\SharedXML\UIDropDownMenu.lua:533 UIDropDownMenu_AddButton()
     Interface\FrameXML\UnitPopup.lua:835 UnitPopup_AddDropDownButton()
     Interface\FrameXML\UnitPopup.lua:622 UnitPopup_ShowMenu()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1454 initFunction()
     Interface\SharedXML\UIDropDownMenu.lua:78 UIDropDownMenu_Initialize()
     Interface\SharedXML\UIDropDownMenu.lua:1055 ToggleDropDownMenu()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:704 <unnamed>:OnClubMemberButtonClicked()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1149
 Interface\FrameXML\StaticPopup.lua:4989 StaticPopup_OnClick()
 An action was blocked because of taint from BlizzMove - GuildLeave()
     Interface\FrameXML\StaticPopup.lua:845 OnAccept()
     Interface\FrameXML\StaticPopup.lua:5021 StaticPopup_OnClick()
     StaticPopup1Button1:OnClick()

**Comment by hn0123** [comment]
This is the new log only blizzmove and taintless.
 Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by BlizzMove - Interface\SharedXML\UIDropDownMenu.lua:37
     securecall()
     Interface\SharedXML\UIDropDownMenu.lua:73 UIDropDownMenu_Initialize()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1440 CommunitiesFrame:UpdateStreamDropDown()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1406 CommunitiesFrame:SelectStream()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1199 CommunitiesFrame:OnClubSelected()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:449 CommunitiesFrame:UpdateSelectedClubInfo()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:440 CommunitiesFrame:SelectClub()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:418 CommunitiesFrame:UpdateClubSelection()
     Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:146
     CommunitiesFrame:Show()
     Interface\FrameXML\UIParent.lua:2915 <unnamed>:SetUIPanel()
     Interface\FrameXML\UIParent.lua:2760 <unnamed>:ShowUIPanel()
     Interface\FrameXML\UIParent.lua:2628
     <unnamed>:SetAttribute()
     Interface\FrameXML\UIParent.lua:3473 ShowUIPanel()
     Interface\FrameXML\UIParent.lua:3434 ToggleFrame()
     Interface\FrameXML\UIParent.lua:1068 ToggleCommunitiesFrame()
     Interface\FrameXML\UIParent.lua:922 ToggleGuildFrame()
     TOGGLEGUILDTAB:1
 Execution tainted by BlizzMove while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\SharedXML\UIDropDownMenu.lua:851 UIDropDownMenu_GetSelectedID()
     Interface\SharedXML\UIDropDownMenu.lua:533 UIDropDownMenu_AddButton()
     Interface\FrameXML\UnitPopup.lua:835 UnitPopup_AddDropDownButton()
     Interface\FrameXML\UnitPopup.lua:622 UnitPopup_ShowMenu()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1454 initFunction()
     Interface\SharedXML\UIDropDownMenu.lua:78 UIDropDownMenu_Initialize()
     Interface\SharedXML\UIDropDownMenu.lua:1055 ToggleDropDownMenu()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:704 <unnamed>:OnClubMemberButtonClicked()
     Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1149
 Interface\FrameXML\StaticPopup.lua:4989 StaticPopup_OnClick()
 An action was blocked because of taint from BlizzMove - GuildLeave()
     Interface\FrameXML\StaticPopup.lua:845 OnAccept()
     Interface\FrameXML\StaticPopup.lua:5021 StaticPopup_OnClick()
     StaticPopup1Button1:OnClick()

**Comment by hn0123** [comment]
This is the new log for all my addons.
  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by BlizzMove - Interface\SharedXML\UIDropDownMenu.lua:37
      securecall()
      Interface\SharedXML\UIDropDownMenu.lua:73 UIDropDownMenu_Initialize()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1440 CommunitiesFrame:UpdateStreamDropDown()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1406 CommunitiesFrame:SelectStream()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:1199 CommunitiesFrame:OnClubSelected()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:449 CommunitiesFrame:UpdateSelectedClubInfo()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:440 CommunitiesFrame:SelectClub()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:418 CommunitiesFrame:UpdateClubSelection()
      Interface\AddOns\Blizzard_Communities\CommunitiesFrame.lua:146
      CommunitiesFrame:Show()
      Interface\FrameXML\UIParent.lua:2915 <unnamed>:SetUIPanel()
      Interface\FrameXML\UIParent.lua:2760 <unnamed>:ShowUIPanel()
      Interface\FrameXML\UIParent.lua:2628
      <unnamed>:SetAttribute()
      Interface\FrameXML\UIParent.lua:3473
      ShowUIPanel()
      Interface\FrameXML\UIParent.lua:3434 ToggleFrame()
      Interface\FrameXML\UIParent.lua:1068 ToggleCommunitiesFrame()
      Interface\FrameXML\UIParent.lua:922 ToggleGuildFrame()
      TOGGLEGUILDTAB:1
  Execution tainted by BlizzMove while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\SharedXML\UIDropDownMenu.lua:851 UIDropDownMenu_GetSelectedID()
      Interface\SharedXML\UIDropDownMenu.lua:533
      UIDropDownMenu_AddButton()
      Interface\FrameXML\UnitPopup.lua:835 UnitPopup_AddDropDownButton()
      Interface\FrameXML\UnitPopup.lua:622 UnitPopup_ShowMenu()
      Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1454 initFunction()
      Interface\SharedXML\UIDropDownMenu.lua:78 UIDropDownMenu_Initialize()
      Interface\SharedXML\UIDropDownMenu.lua:1055 ToggleDropDownMenu()
      Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:704 <unnamed>:OnClubMemberButtonClicked()
      Interface\AddOns\Blizzard_Communities\CommunitiesMemberList.lua:1149
  Interface\FrameXML\StaticPopup.lua:4989 StaticPopup_OnClick()
  An action was blocked because of taint from BlizzMove - GuildLeave()
      Interface\FrameXML\StaticPopup.lua:845 OnAccept()
      Interface\FrameXML\StaticPopup.lua:5021 StaticPopup_OnClick()
      StaticPopup1Button1:OnClick()

**Comment by Numynum** [comment]
thanks for the info, should be fixed in the next version (v3.0.13, which should be available on curse shortly)
