### ISSUE TITLE
Error when editing roles in Guild/Community panels.

### ISSUE THREAD

**Issue by VXLDXMXR** [Kiatra/BlizzMove#61]
3x [ADDON_ACTION_FORBIDDEN] AddOn 'BlizzMove' tried to call the protected function 'SetGuildRankOrder()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetGuildRankOrder'
[string "@Blizzard_Communities\GuildRoster.lua"]:174: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:905: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by EnserNG** [comment]
Was leaving a comment about this, myself - this happens when changing a note in either guild or community, as well.  It does not error if you disable BlizzMove's ability to reposition the frame.

**Comment by Numynum** [comment]
thanks for the info, should be fixed in the next version (v3.0.13, which should be available on curse shortly)
