### ISSUE TITLE
Issue when attempting to cast spell from spellbook

### ISSUE THREAD

**Issue by ZoombieDyl** [Kiatra/BlizzMove#62]
I can't seem to reproduce the error, nor does a console error popup but whenever I try and click a spell from my spellbook a blizzard pop-up appears that says

"BlizzMove has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI."

I disabled other addons to ensure that it was BlizzMove causing the issue.

Like I said, it leaves no console or error files so I don't have much I could post for help

**Comment by Numynum** [comment]
thanks for the info, should be fixed in the next version (v3.0.13, which should be available on curse shortly)
