### ISSUE TITLE
Suggestion: Options for default move key

### ISSUE THREAD

**Issue by solitha** [Kiatra/BlizzMove#66]
I love the functionality except it's so easy to move frames that I'm _constantly_ doing it on accident just trying to click on things like selections in the window. I request the option to change the default left click to move, to something a little more deliberate. The default action bars allow you to shift-left click to move things around when they're locked. Could that be an option in this addon as well?

**Comment by zaCade** [comment]
Added an option to require holding shift in v3.0.18. Reason shift was chosen is because shift+RMB is move reset, so now shift+LMB is move, if the toggle is enabled in the options.
