### ISSUE TITLE
[BCC] Social frame (who tab) breaking player menu.

### ISSUE THREAD

**Issue by Road-block** [Kiatra/BlizzMove#73]
Quote from Fred7 >>
> tbc v3.1.3bcc

> no addons loaded except for blizmove
> you are breaking the right click functionality of the who window.
> I should be able to right click peoples names in the social window who tab and get a right click menue with target/ignore/etc
 

> edit: this only happens if the who tab has a lot of people (is scrollable).

[Original post](https://www.curseforge.com/wow/addons/blizzmove?comment=419)

This is still an issue with current version.

**Comment by Numynum** [comment]
hm strange, that was supposed to be fixed with v3.1.4bcc; and the guy who originally reported it confirmed it as working on discord
I'll try to take a look again sometime soon

could you try v3.1.4, and check if it's broken there? (assuming you tried 3.1.7)

**Comment by Road-block** [comment]
> hm strange, that was supposed to be fixed with v3.1.4bcc; and the guy who originally reported it confirmed it as working on discord I'll try to take a look again sometime soon
> 
> could you try v3.1.4, and check if it's broken there? (assuming you tried 3.1.7)

Couldn't reproduce in 3.1.7, 
The behavior was that not the whole scrollchild was broken, the top 4-5 names might work then from some point down the list right-clicking to get the playermenu would silently fail. (as if there was some clipping happening)  

It seems to be working in latest 3.1.7, if there have been no changes from 3.1.6 that would affect this issue specifically there's a chance I had an older version than I thought. 

Sorry for the false alarm; tried a few /who requests with scroll list showing and I can't reproduce it. safe to close I'd say.
