### ISSUE TITLE
lua error with "zoomLevel"

### ISSUE THREAD

**Issue by MyTechnoHunter** [Kiatra/BlizzMove#74]
11x SharedXML\ModelFrames.lua:116: attempt to perform arithmetic on local 'zoomLevel' (a boolean value)
[string "@SharedXML\ModelFrames.lua"]:116: in function `OnMouseWheel'
[string "@BlizzMove\BlizzMove-v3.1.7.lua"]:614: in function <BlizzMove\BlizzMove.lua:607>
[string "@BlizzMove\BlizzMove-v3.1.7.lua"]:618: in function <BlizzMove\BlizzMove.lua:607>
[string "@BlizzMove\BlizzMove-v3.1.7.lua"]:634: in function <BlizzMove\BlizzMove.lua:624>
[string "=(tail call)"]: ?

Locals:
self = CharacterModelFrame {
 minZoom = 0
 maxZoom = 0.800000
 rotation = 0.610000
 0 = <userdata>
 defaultRotation = 0.610000
 onMouseUpFunc = <function> defined @SharedXML\ModelFrames.lua:106
}
delta = -1
maxZoom = 0.800000
minZoom = true
zoomLevel = true
(*temporary) = -0.150000
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'zoomLevel' (a boolean value)"

The above happened when i opened the skill windows with the "k" key and then tried to mousewheel to move the list up and down to see what skills were lower in the window..

**Comment by MyTechnoHunter** [comment]
this is on BCC

**Comment by Numynum** [comment]
hi, I couldn't reproduce this issue myself; but I think it's fixed in the latest update
