### ISSUE TITLE
Anima Power frame

### ISSUE THREAD

**Issue by rml9ty** [Kiatra/BlizzMove#76]
I would very much like to move/hide this frame. (Current M+ affix power thingy)

https://i.imgur.com/crO2BKW.jpg

**Comment by Numynum** [comment]
I don't actively play atm, so can't check for sure, but the torghast version of that frame is part of the objective tracker; which you can move with this plugin https://www.curseforge.com/wow/addons/blizzmove-plugin-questtracker

to hide the frame, you can make a macro with `/run ScenarioBlocksFrame.MawBuffsBlock:Hide()` or something
