### ISSUE TITLE
Blizzard Vendor UI Showing With TSM Addon

### ISSUE THREAD

**Issue by Lissard** [Kiatra/BlizzMove#77]
Hi,

There is an auction addon called TSM which among other things replaces the Blizzard vendor UI with their own that can be toggled between the TSM vendor UI and the Blizzard vendor UI.  When you open a vendor it shows the TSM UI and hides the Blizzard one and vice versa on toggle.  

Since earlier this week when using the TSM vendor UI, the Blizzard one also shows at all times.  This can be replicated with only TSM & BlizzMove enabled and upon disabling BlizzMove the Blizzard vendor UI is successfully hidden when using the TSM vendor UI.

Thanks.

![image](https://user-images.githubusercontent.com/32798835/140101221-c3997e4a-7dcc-4661-bb99-e8794247fc85.png)

**Comment by Numynum** [comment]
Hi, try and see what happens if you disable MerchantFrame in the BlizzMove config (and reload ui after you disabled it)

**Comment by Numynum** [comment]
In general though, I'd consider this a TSM problem, not a BlizzMove problem, especially if this started recently (try see if it works fine with an older TSM version for example)
