### ISSUE TITLE
lua error with latest blizzmove.

### ISSUE THREAD

**Issue by MyTechnoHunter** [Kiatra/BlizzMove#78]
the following occurs on opening any blizz window.. c to open char screen, o to open friends list.. 

did a clean install of the plugin to make sure it wasnt holding on to any old info

2x BlizzMove\BlizzMove-v3.2.0.lua:471: attempt to index field 'storage' (a nil value)
[string "@BlizzMove\BlizzMove-v3.2.0.lua"]:471: in function <BlizzMove\BlizzMove.lua:462>
[string "@BlizzMove\BlizzMove-v3.2.0.lua"]:495: in function <BlizzMove\BlizzMove.lua:491>
[string "@BlizzMove\BlizzMove-v3.2.0.lua"]:684: in function <BlizzMove\BlizzMove.lua:678>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:2073: in function `SetUIPanel'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:1918: in function `ShowUIPanel'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:1779: in function <Interface_TBC\FrameXML\UIParent.lua:1775>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:2544: in function <Interface_TBC\FrameXML\UIParent.lua:2523>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:1139: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals:
frame = FriendsFrame {
 0 = <userdata>
 TitleText = FriendsFrameTitleText {
 }
 portrait = FriendsFramePortrait {
 }
 LeftBorder = FriendsFrameLeftBorder {
 }
 SetHeight = <function> defined =[C]:-1
 SetPoint = <function> defined =[C]:-1
 selectedFriend = 1
 Inset = FriendsFrameInset {
 }
 FriendsTabHeader = FriendsTabHeader {
 }
 selectedFriendType = 2
 TopRightCorner = FriendsFrameTopRightCorner {
 }
 TopLeftCorner = FriendsFrameTopLeftCorner {
 }
 Bg = FriendsFrameBg {
 }
 playerStatusFrame = 1
 guildStatus = 0
 TopBorder = FriendsFrameTopBorder {
 }
 selectedIgnore = 1
 TopTileStreaks = FriendsFrameTopTileStreaks {
 }
 TitleBg = FriendsFrameTitleBg {
 }
 BottomBorder = FriendsFrameBottomBorder {
 }
 selectedSquelchType = 2
 OnLoad = <function> defined @SharedXML\SharedUIPanelTemplates.lua:857
 numTabs = 4
 BotRightCorner = FriendsFrameBotRightCorner {
 }
 SetWidth = <function> defined =[C]:-1
 CloseButton = FriendsFrameCloseButton {
 }
 BotLeftCorner = FriendsFrameBotLeftCorner {
 }
 PortraitFrame = FriendsFramePortraitFrame {
 }
 selectedTab = 1
 RightBorder = FriendsFrameRightBorder {
 }
}
frameData = <table> {
 MinVersion = 0
 SubFrames = <table> {
 }
 storage = <table> {
 }
}
returnValue = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 IgnoreListFrameScrollFrame = <table> {
 }
 FriendsFrameBattlenetFrame.BroadcastFrame = <table> {
 }
 FriendsListFrameScrollFrame = <table> {
 }
 QuickJoinScrollFrame = <table> {
 }
 RaidInfoFrame = <table> {
 }
 WhoListScrollFrame = <table> {
 }
 RecruitAFriendFrame.RecruitList.ScrollFrame = <table> {
 }
}
(for control) = "IgnoreListFrameScrollFrame"
_ = "IgnoreListFrameScrollFrame"
subFrameData = <table> {
 MinVersion = 40000
}
(*temporary) = nil
(*temporary) = <table> {
 MinVersion = 40000
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'storage' (a nil value)"
BlizzMove = <table> {
 SetDefaultModuleLibraries = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Frames = <table> {
 }
 EnableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "BlizzMove"
 IterateEmbeds = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ValidateFrame = <function> defined @BlizzMove\BlizzMove.lua:45
 SecureHookScript = <function> defined @BlizzMove\Libs\AceHook-3.0\AceHook-3.0.lua:410
 enabled = true
 RawHookScript = <function> defined @BlizzMove\Libs\AceHook-3.0\AceHook-3.0.lua:395
 RegisterFrame = <function> defined @BlizzMove\BlizzMove.lua:112
 ValidateFrameName = <function> defined @BlizzMove\BlizzMove.lua:51
 CopyTable = <function> defined @BlizzMove\BlizzMove.lua:334
 SetDefaultModulePrototype = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 EnableFrame = <function> defined @BlizzMove\BlizzMove.lua:208
 defaultModuleState = true
 IsEnabled = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 GetFrameFromName = <function> defined @BlizzMove\BlizzMove.lua:271
 DisableModule = <function> defined @DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 ResetScaleStorage = <function> defined @BlizzMove\BlizzMove.lua:291
 ADDON_LOADED = <function> defined @BlizzMove\BlizzMove.lua:977
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsHooked = <function> defined @BlizzMove\Libs\AceHook-3.0\AceHook-3.0.lua:493
 DebugPrint = <function> defined @BlizzMove\BlizzMove.lua:38
 DisableFrame = <function> defined @BlizzMove\BlizzMove.lua:199
 UnregisterFrame = <function> defined @BlizzM

**Comment by MyTechnoHunter** [comment]
reverted to the previous version, no error. dunno if that helps but there ya go.. (in case this wasnt clear, this is in TBC)

**Comment by Numynum** [comment]
hi, should be fixed in v3.2.0a, downloadable soon™ :)
