### ISSUE TITLE
Collections Tab wont move

### ISSUE THREAD

**Issue by Niyuni** [Kiatra/BlizzMove#79]
Hi there, 

i really love this Addon and i dont want to miss this little diamond :) 

Everythings works fine except "Collections Tab". Seems bugged?
There is no error message or anything. Tabs just blacksout like this https://imgur.com/a/qXOQK3m. Need to close  and reopen it to work again properly but i cant move it. 
I also deactivated all other addons except BlizzMove... :(

Just wondering if anyone else having the same issue.

**Comment by Numynum** [comment]
Hi, you're right, I have the same issue as well, for now you can use an older blizzmove version, or disable collectionsJournal in /bm settings (it's under Blizzard_Collections)

I'll update here when it's fixed (might take a bit, because I don't actively play currently)

**Comment by Numynum** [comment]
seems there's something broken with the collection UI, which sadly has nothing to do with blizzmove, so using an old version won't help
I've narrowed it down to the specific issue, but I'm somewhat clueless on how to fix it tbh..
what I have found out, is that if you open the transmog ui first, then you can move the collections ui without any issue

it's very annoying, but right now, that's the only workaround I could find -.-

**Comment by linaori** [comment]
I've had this issue for a while, it triggers once I move the UI and it also randomly "crashes". Oddly enough I have the issue with ElvUI Windtools as well, so it seems to be an issue within the default UI.

**Comment by Numynum** [comment]
Hi, correct, it's a default ui issue, telling the default ui to start moving the collection ui, will break it
unless you open the transmog ui first /shrug

**Comment by Numynum** [comment]
I've disabled the collection ui and transmog ui for now; until blizzard fixes this (I wasn't able to find a decent working fix unfortunately)
