### ISSUE TITLE
blizzmove reports and error. (SoM/classic version)

### ISSUE THREAD

**Issue by MyTechnoHunter** [Kiatra/BlizzMove#81]
![image](https://user-images.githubusercontent.com/55214545/142700265-2374d591-7ef8-4b02-bff3-93d37b4fa346.png)

to reproduce, open the talent window with the n button

**Comment by Numynum** [comment]
fixed in v3.2.5 (downloadable soon ™)

**Comment by MyTechnoHunter** [comment]
sounds good! thanks
