### ISSUE TITLE
Version v3.2.6 Local(error)

### ISSUE THREAD

**Issue by Vyrazz** [Kiatra/BlizzMove#82]
Received LUA error for your perusal on version v3.2.6 as below :

11x [ADDON_ACTION_BLOCKED] AddOn 'BlizzMove' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3508: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2576: in function `LFGListSearchEntry_OnEnter'
[string "@FrameXML\LFGList.lua"]:2523: in function `LFGListSearchEntry_Update'
[string "@FrameXML\LFGList.lua"]:2159: in function `LFGListSearchPanel_UpdateResults'
[string "@FrameXML\LFGList.lua"]:1932: in function `update'
[string "@SharedXML\HybridScrollFrame.lua"]:193: in function `HybridScrollFrame_SetOffset'
[string "@SharedXML\HybridScrollFrame.lua"]:30: in function <SharedXML\HybridScrollFrame.lua:29>
[string "=[C]"]: in function `SetValue'
[string "@SharedXML\HybridScrollFrame.lua"]:67: in function <SharedXML\HybridScrollFrame.lua:57>
[string "=[C]"]: in function `OnMouseWheel'
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:648: in function <BlizzMove\BlizzMove.lua:640>
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:653: in function <BlizzMove\BlizzMove.lua:640>
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:653: in function <BlizzMove\BlizzMove.lua:640>
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:653: in function <BlizzMove\BlizzMove.lua:640>
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:653: in function <BlizzMove\BlizzMove.lua:640>
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:669: in function <BlizzMove\BlizzMove.lua:659>
[string "@BlizzMove\BlizzMove-v3.2.6.lua"]:672: in function <BlizzMove\BlizzMove.lua:659>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

**Comment by Numynum** [comment]
generally, this is blizzard's fault, for (needlessly) making GetPlaystyleString a protected function
a lot of addons are suffering because of this

we may or may not look at implementing a workaround
does this stop any LFG features from working?

**Comment by Numynum** [comment]
turns out there's a workaround available. should still complain to blizzard though :p

**Comment by Vyrazz** [comment]
LoL..Yeahh..Its blizzard side but all good my friend..Its like a minor bug so yeah just helping to post to help on the errors thingy..Cheerss!
