### ISSUE TITLE
LUA error when attempting to look at rewards on adventure guide

### ISSUE THREAD

**Issue by James1o1o** [Kiatra/BlizzMove#84]
Within the adventure guide, when you go to highlight the little reward orbs to see what items/rewards you gain, WoW will throw up an LUA error when BlizzMove is enabled. Will put the entire error in quotes bellow.

![1](https://user-images.githubusercontent.com/29644651/147566769-7cc9d0d0-23e3-4ed4-b008-6587cfb8f3f4.png)

![2](https://user-images.githubusercontent.com/29644651/147566772-a24f3ea2-f92f-4733-97ed-8455691c087d.png)

> Message: ...zzard_EncounterJournal\Blizzard_EncounterJournal.lua:3213: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: EncounterJournalTooltip:SetPoint.
Time: Tue Dec 28 12:35:12 2021
Count: 6
Stack: ...zzard_EncounterJournal\Blizzard_EncounterJournal.lua:3213: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: EncounterJournalTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\Blizzard_EncounterJournal\Blizzard_EncounterJournal.lua"]:3213: in function <...zzard_EncounterJournal\Blizzard_EncounterJournal.lua:3209>

>Locals: (*temporary) = EncounterJournalTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:12
 GetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:182
 SetupTextureCoordinates = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:16
 OnBackdropSizeChanged = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:13
 HasBackdropInfo = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:18
 SetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:186
 layoutType = "TooltipDefaultLayout"
 Item1 = EncounterJournalTooltipItem1 {
 }
 GetEdgeSize = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:14
 NineSlice = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:194
 headerText = EncounterJournalTooltipHeaderText {
 }
 ApplyBackdrop = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:22
 TooltipBackdropOnLoad = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:163
 ClearBackdrop = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:34
 Item2 = EncounterJournalTooltipItem2 {
 }
 GetBackdropBorderColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:190
 GetBackdrop = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:19
 GetBackdropCoordValue = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:15
 SetupPieceVisuals = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:17
 SetBackdropColor = <function> defined @Interface\SharedXML\SharedTooltipTemplates.lua:178
 SetBackdrop = <function> defined @Interface\AddOns\Blizzard_Deprecated\Deprecated_9_1_5.lua:27
 clickText = EncounterJournalTooltipClickText {
 }
}
(*temporary) = "BOTTOMLEFT"
(*temporary) = <unnamed> {
 0 = <userdata>
 iconRingHighlight = <unnamed> {
 }
 data = <table> {
 }
 iconRing = <unnamed> {
 }
 icon = <unnamed> {
 }
 text = <unnamed> {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 0
(*temporary) = 0

**Comment by Numynum** [comment]
hi, we've seen this type of issue before, and it can be a bit hard to find and fix

for reference, this error shows up if you hover over an icon after moving the frame
and if you try to move the frame after (successfully) showing a tooltip, then the whole frame breaks

**Comment by Numynum** [comment]
as a workaround, you can disable moving the encounter journal in blizzmove settings (`/bm`)

**Comment by Numynum** [comment]
should be fixed next version
