### ISSUE TITLE
Incorrect classic/SoM interface version

### ISSUE THREAD

**Issue by MyTechnoHunter** [Kiatra/BlizzMove#85]
in the addon for classic/SoM the latest update changed the retail .toc file to use the updated interface version but the classic toc file (for both the addon and the debug) still has  ## Interface: 11401 instead of ## Interface: 11402

thank you for your time

**Comment by Numynum** [comment]
fixed in v3.2.13
just as an fyi, none of the contributors actively play or track classic/tbc, so if it takes a while before the classic version's toc bump, feel free to say so again 👌
