### ISSUE TITLE
PVEFrame scale is not persistent

### ISSUE THREAD

**Issue by Tarkumi** [Kiatra/BlizzMove#88]
Every time I relog/reload the PVEFrame (Group Finder) scale is resetting to default.
All other frames' scaling data are persistent between sessions.
Version: Retail 9.2.0

**Comment by Numynum** [comment]
it seems some other addon is causing this.
try disabled all addons except blizzmove, and if it works, enable a few addons at a time, to see what breaks it
if you tell us what addon breaks it, we can see if it's something we can/want to fix, or if you should make an issue on their end :)

**Comment by Tarkumi** [comment]
Thanks for the tip.
Premade Groups Filter is causing the problem.
It uses SetScript instead of HookScript to set it's event handler to PVEFrame.
I will contact it's author to correct the code.

**Comment by Numynum** [comment]
thanks for the heads-up, I'll close this issue then :)
