### ISSUE TITLE
Lua errors and windows do not save positions if I log out; they reset to defaults when I log back in

### ISSUE THREAD

**Issue by bmonterosso** [Kiatra/BlizzMove#91]
Message: ...\AddOns\BlizzMove\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "NEW_PET_ADDED"
Time: Thu Sep  8 21:53:10 2022
Count: 1
Stack: ...\AddOns\BlizzMove\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "NEW_PET_ADDED"
[string "=(tail call)"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\BlizzMove\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\HandyNotes_Collection\Class\HandyNotes.lua"]:221: in function <...ce\AddOns\HandyNotes_Collection\Class\HandyNotes.lua:213>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

My windows do not remember where I move them to, once I log and back in, they reset. Not sure if it's related to the window position not saving, but figured you might want to know.

**Comment by Numynum** [comment]
Hi, HandyNotes_Collection is the actual cause of that error, you should report it there instead :)

Regarding positions not saving, have you enabled that setting in the blizzmove config? (Type `/bm`, and check the 3rd tab)
if it is enabled, try disable all addons except blizzmove, and see if it works then
