### ISSUE TITLE
WOTLK Classic Update

### ISSUE THREAD

**Issue by maximus210793** [Kiatra/BlizzMove#92]
Hi,
Can you update for WOTLK Classic please?
For example I can no longer move the Character Info Window. When I do so the windows bugs out and nothing is displayed in the windows anymore.
Would be awesome, thanks a lot!

**Comment by Numynum** [comment]
Hi,
what version are you using? Blizzmove has been compatible for over a month now
does the character info window bug out if you disable all other addons?

**Comment by Road-block** [comment]
These are relevant callstacks from comment [478](https://www.curseforge.com/wow/addons/blizzmove?comment=478) and 479

Far as I can tell the addon that breaks CharacterFrame movement for BlizzMove is RestedXP, the Leveling Tracker module that attaches to CharacterFrame.

**Comment by Numynum** [comment]
Hi, this is an issue with RestedXP addon, not BlizzMove
see https://github.com/Kiatra/BlizzMove/issues/93
