### ISSUE TITLE
CharacterFrame error when moving

### ISSUE THREAD

**Issue by nlautner10** [Kiatra/BlizzMove#93]
CharacterFrame won't move and blanks out when trying to move it.

```
Message: Interface\AddOns\BlizzMove\BlizzMove-v3.4.5.lua:388: attempt to perform arithmetic on a nil value
Time: Wed Sep 21 15:50:21 2022
Count: 1
Stack: Interface\AddOns\BlizzMove\BlizzMove-v3.4.5.lua:388: attempt to perform arithmetic on a nil value
[string "=(tail call)"]: ?

Locals: (*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1
```

After investigating, GetLeft(), GetTop(), etc all return nil within GetAbsoluteFramePosition(...)

I also enabled debug printing and got the following by pressing 'c' to open character frame, then left click, drag, release.
```
[15:51:53] BlizzMove: Debug message:
 OnShow: PaperDollFrame
[15:51:53] BlizzMove: Debug message:
 OnShow: CharacterFrame
[15:51:55] BlizzMove: Debug message:
 OnMouseDown: CharacterFrame LeftButton
[15:51:56] BlizzMove: Debug message:
 OnMouseUp: CharacterFrame LeftButton
[15:51:56] BlizzMove: Debug message:
 Processing global MouseUp event after sub-frame got hidden
[15:51:56] BlizzMove: Debug message:
 OnMouseUp: CharacterFrame LeftButton
```

**Comment by Numynum** [comment]
hi, is this retail or classic?
does it work properly if you have all other addons except blizzmove disabled?

**Comment by nlautner10** [comment]
Classic

It appears to be an interaction with RXPGuides addon. Issue no longer persists with RXPGuides disabled.

**Comment by Numynum** [comment]
this was actually mentioned a few hours ago on the discord :)

> There is 3 things you can do here
> 1. disable the char frame in blizzmove, so you cant move it
> 2. disable the leveling tracker in restedxp, this is whats anchored wrong. (And thus causing the issue)
> 3. report the issue to the addon creators
