### ISSUE TITLE
A way to move the durability doll when equipment is broken/almost broken?

### ISSUE THREAD

**Issue by robmonte** [Kiatra/BlizzMove#94]
### What game version did the bug occur in?

Wrath of the Lich King Classic

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

Couldn't find a way to move the durability doll that shows you when equipment is breaking. Not really a bug if the feature is absent/hidden, but if it's supposed to just drag then I couldn't do so.

### Steps to reproduce.

Try moving the durability doll when it appears with broken equipment.

### Expected behavior.

It should be moveable.

**Comment by Numynum** [comment]
hi, in general, BlizzMove only allows you to move frames that look and feel like UI windows
a rule of thumb is, if it's got a title bar, BlizzMove will move it

the durability doll frame doesn't really fit that, and I would generally advise moving it with addons such as MoveAnything, ElvUI, or similar instead 🙂
