### ISSUE TITLE
[Bug Report] AddOn 'BlizzMove' tried to call the protected function 'UseContainerItem()'.

### ISSUE THREAD

**Issue by drnoonien** [Kiatra/BlizzMove#97]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

I cannot use items in my bags.

### Steps to reproduce.

- Install BlizzMove
- Try to use a consumable in your bags, i.e. water/food

### Expected behavior.

Clicking items in my bag should work.

### Errors

```lua
1x [ADDON_ACTION_FORBIDDEN] AddOn 'BlizzMove' tried to call the protected function 'UseContainerItem()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1384: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1435: in function <Interface/FrameXML/ContainerFrame.lua:1423>
```

**Comment by drnoonien** [comment]
The culprit seems to be this block of code. Commenting it out resolves the issue. I'm sure it breaks something else instead however.

https://github.com/Kiatra/BlizzMove/blob/master/BlizzMove.lua#L1211

```lua
if self.gameVersion >= 100000 then
	-- fix anchor family connection issues with the combined bag
	self:RawHook("UpdateContainerFrameAnchors", function()
		for _, frame in ipairs(ContainerFrameSettingsManager:GetBagsShown()) do
			frame:ClearAllPoints();
		end
		self.hooks.UpdateContainerFrameAnchors();
	end, true);
end
```

**Comment by Numynum** [comment]
hi, you're correct
and the main thing it'll break is bank bags, and the reagent bag (when dragonflight itself releases)

we're looking into alternative fixes atm

**Comment by Numynum** [comment]
we're having trouble properly reproducing the problem, but it should hopefully be resolved in the next update
if you could confirm if it works, that'd be great :)

**Comment by drnoonien** [comment]
Seems to be fixed as of the latest update.

**Comment by Numynum** [comment]
we've had some other users saying the same, glad to have confirmation :)
