### ISSUE TITLE
Profession frame forgets resize when Crafted Items window appears

### ISSUE THREAD

**Issue by TeiranDragon** [Kiatra/BlizzMove#98]
Each time I craft an item and the new "Crafted Items" side window pops up, the new Dragonflight profession frame jumps back to full size. 

If I close it, it remembers the scale and location I set it too when opening. If I scale the window while the "Crafted Items" side window is open, it does no resize when I craft the next item. But if I close the "Crafted Items" side frame and craft again, the main profession frame pops right back to full size.

This can cause other frames like the merchant to close depending on the UI scale, because if I scale my UI down far enough, the profession frame won't close the merchant or bag frames when it resizes.

**Comment by Numynum** [comment]
should be fixed in the next update
