### ISSUE TITLE
[Bug Report] Moved windows will lose native Blizzard stickiness

### ISSUE THREAD

**Issue by Gerokusu** [Kiatra/BlizzMove#99]
### What game version did the bug occur in?

Retail

### Troubleshooting

- [X] I have verified that BlizzMove is up to date.
- [X] I have tried to reproduce the bug with no other addons loaded.
- [X] I have verified that the issue hasn't yet been reported.

### Describe the bug.

When I use BlizzardMove to reposition menu windows permanently (such as Character View, Map / Quests, Spells...), they lose this functionality to stick horizontally to each other.

### Steps to reproduce.

Open the Character Window and Spell Window. Move both somewhere. Close them. Open them again.

### Expected behavior.

The windows somehow sticks to each other, in any order.

### Errors

```lua
The windows are overlapping.
```

**Comment by Gerokusu** [comment]
Before :

![github_issue_before](https://user-images.githubusercontent.com/5943570/198723744-afcbd54d-cd83-403e-a8b0-84580ea50c12.png)

After :

![github_issue_after](https://user-images.githubusercontent.com/5943570/198723800-0d7d26dc-4c65-49b9-a44b-4f3c6e26f4b0.png)

**Comment by Numynum** [comment]
hi, this is intended behaviour
Permanently moved frames have their positions restored when you open them, which override blizzard positioning
if you want blizzard behaviour, then switch back to not remembering positions at all :)
